apiVersion: v1
kind: Service
metadata:
  name: client-svc
spec:
  type: NodePort
  selector:
    app: client
  ports:
  - name: client
    port: 3000
    protocol: TCP
    targetPort: 3000
    nodePort: 30081