version: '3.9'

services:
  
  client:
    image: client:v0.1
    container_name: project-client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8081
    ports:
      - 3000:3000

  server:
    image: server:v0.1
    container_name: project-server
    build:
      context: ./server
      dockerfile: Dockerfile
    environment:
      - PORT=8081
    ports:
      - 8081:8081
