apiVersion: v1
kind: Service
metadata:
  name: log-output-svc
  namespace: pingpong-log
spec:
  type: NodePort
  selector:
    app: log-output
  ports:
    - name: reader
      port: 80
      protocol: TCP
      targetPort: 3001