apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: pingpong-log
spec:
  type: NodePort
  selector:
    app: pingpong
  ports:
  - name: pingpong
    port: 80
    protocol: TCP
    targetPort: 5000
