apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: pingpong-log
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
  - port: 80
    protocol: TCP
    targetPort: 5000
