apiVersion: apps/v1
kind: Deployment
metadata:
  name: pingpong-dep
  namespace: pingpong-log
spec:
  replicas: 1
  selector:
    matchLabels:
      app: pingpong
  template:
    metadata:
      labels:
        app: pingpong
    spec:
      containers:
      - name: pingpong
        image: sirpacoder/pingpong:v4.01
        imagePullPolicy: Always
        env:
          - name: PORT
            value: "5000"
          - name: POSTGRES_HOST
            value: postgres-svc
          - name: POSTGRES_USER
            valueFrom:
              configMapKeyRef:
                name: config-env-variables
                key: postgres_user
          - name: POSTGRES_DB
            valueFrom:
              configMapKeyRef:
                name: config-env-variables
                key: postgres_db
        envFrom:
          - secretRef:
              name: postgres-pw
        readinessProbe:
          initialDelaySeconds: 10
          periodSeconds: 5
          failureThreshold: 10
          httpGet:
            path: /healthz
            port: 5000
        resources:
          requests:
            memory: "64Mi"
            cpu: "250m"
          limits:
            memory: "516Mi"
            cpu: "500m"

---

apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: pingpong-log
spec:
  type: ClusterIP
  selector:
    app: pingpong
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000