apiVersion: apps/v1
kind: Deployment
metadata:
  name: log-output-dep
spec:
  replicas: 1
  selector:
    matchLabels:
      app: log-output
  template:
    metadata:
      labels:
        app: log-output
    spec:
      volumes:
        - name: shared-files
          emptyDir: {}
      containers:
      - name: writer
        image: k3d-registry:5000/writer:latest
        volumeMounts:
          - name: shared-files
            mountPath: /shared/files
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
      - name: reader
        image: k3d-registry:5000/reader:latest
        env:
          - name: PINGPONG_URL
            value: http://pingpong-svc:6661
        volumeMounts: # Mount volume
          - name: shared-files
            mountPath: /shared/files
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"