version: '3.9'

services:
  
  client:
    image: client:v2.08
    container_name: client
    build:
      context: ./client
      dockerfile: Dockerfile
    environment:
      - REACT_APP_SERVER_URL=http://localhost:8082
    ports:
      - 3000:3000

  server:
    image: server:v2.08
    container_name: server
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    environment:
      - PORT=8082
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres
  
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - ./database:/var/lib/postgresql/data

volumes:
    database:
        driver: local