version: '3.9'

services:
  postgres:
    image: postgres:alpine
    container_name: postgres
    restart: unless-stopped
    ports:
      - 5432:5432
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
    volumes:
      - ./database:/var/lib/postgresql/data

  pingpong:
    platform: linux/amd64
    image: pingpong:v3.01
    container_name: pingpong
    build:
      context: ./pingpong
      dockerfile: Dockerfile
    ports:
      - 5000:5000
    environment:
      - POSTGRES_HOST=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=postgres
      - POSTGRES_PORT=5432
    depends_on:
      - postgres

volumes:
    database:
        driver: local