apiVersion: v1
kind: Service
metadata:
  name: pingpong-svc
  namespace: pingpong-log
spec:
  type: LoadBalancer # This should be the only unfamiliar part
  selector:
    app: pingpong
  ports:
    - name: http
      port: 80
      protocol: TCP
      targetPort: 5000

# apiVersion: v1
# kind: Service
# metadata:
#   name: pingpong-svc
#   namespace: pingpong-log
# spec:
#   type: ClusterIP
#   selector:
#     app: pingpong
#   ports:
#   - name: pingpong
#     port: 6661
#     protocol: TCP
#     targetPort: 5000
  