apiVersion: apps/v1
kind: Deployment
metadata:
  name: client-dep
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: client
  template:
    metadata:
      labels:
        app: client
    spec:
      containers:
      - name: client
        image: sirpacoder/client:v3.03
        imagePullPolicy: Always
        env:
          - name: REACT_APP_SERVER_URL
            valueFrom:
              configMapKeyRef:
                name: config-env-variables
                key: server-url
        resources:
          requests:
            memory: '32Mi'
            cpu: '200m'
          limits:
            memory: '64Mi'
            cpu: '250m'

---

  apiVersion: v1
  kind: Service
  metadata:
    name: client-svc
    namespace: project
  spec:
    type: NodePort
    selector:
      app: client
    ports:
    - name: client
      port: 80
      protocol: TCP
      targetPort: 3000
      nodePort: 30081