apiVersion: apps/v1
kind: Deployment
metadata:
  name: server-deployment
  namespace: project
spec:
  replicas: 1
  selector:
    matchLabels:
      app: server
  template:
    metadata:
      labels:
        app: server
    spec:
      containers:
      - name: server
        image: sirpacoder/server:v0.1
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"