apiVersion: batch/v1
kind: CronJob
metadata:
  name: wiki-url
  namespace: project
spec:
  schedule: "* 10 * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
          - name: wiki-url
            image: sirpacoder/wiki_url:v2.09
            env:
              - name: SERVER_URL
                value: http://server-svc:6662/api/todos
            imagePullPolicy: Always
          restartPolicy: OnFailure