# service.yml
apiVersion: v1
kind: Service
metadata:
  name: postgres-loadbalancer
spec:
  selector:
    app: postgres-db
  type: LoadBalancer
  ports:
    - port: 5432
      targetPort: 5432

---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: postgres-db
spec:
  selector:
    matchLabels:
      app: postgres-db
  serviceName: postgres-db-svc
  replicas: 2
  template:
    metadata:
      labels:
        app: postgres-db
    spec:
      containers:
      - name: postgres-db
        image: postgres:latest
        volumeMounts:
          - name: postgres-data
            mountPath:  /usr/src/app/data
      env:
        - name: PGDATA
          value: /usr/src/app/data/pgdata
      envFrom:
        - secretRef:
            
  volumeClaimTemplates:
  - metadata:
      name: postgres-data
    spec:
      accessModes: [ "ReadWriteOnce" ]
      resources:
        requests:
          storage: 1Gi
